"""Update Category and Question models

Revision ID: 5a05bce59493
Revises: 9781a2475295
Create Date: 2024-07-28 19:44:11.400704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a05bce59493'
down_revision = '9781a2475295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_name', ['name'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name', type_='unique')

    # ### end Alembic commands ###