"""Initial migration.

Revision ID: 9781a2475295
Revises: 9d6110ddfcb5
Create Date: 2024-07-28 19:04:11.598959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9781a2475295'
down_revision = '9d6110ddfcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'category' not in inspector.get_table_names():
        op.create_table('category',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=80), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_question_category', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_response_question', 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint('fk_response_question', type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constrai